version: '3.7'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 80:80
    depends_on:
      - db
    env_file:
      - ./backend/.env   

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./data/transformed_energy_data.csv:/docker-entrypoint-initdb.d/data.csv
    env_file:
      - ./backend/.env  

